// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
#deprecated
pub extend ArrowheadType with Debug::{to_repr}

///|
#deprecated
pub extend ArrowheadType with Eq::{not_equal, equal}

///|
#deprecated
pub extend ArrowheadType with Show::{output}

///|
#deprecated
pub extend Box with Debug::{to_repr}

///|
#deprecated
pub extend Box with Eq::{not_equal, equal}

///|
#deprecated
pub extend Box with Show::{output}

///|
#deprecated
pub extend EdgeInput with Debug::{to_repr}

///|
#deprecated
pub extend EdgeModel with Debug::{to_repr}

///|
#deprecated
pub extend EdgeReference with Debug::{to_repr}

///|
#deprecated
pub extend EdgeReference with Eq::{not_equal, equal}

///|
#deprecated
pub extend FragmentOperandInput with Debug::{to_repr}

///|
#deprecated
pub extend FragmentOperandLayout with Debug::{to_repr}

///|
#deprecated
pub extend FragmentOperandModel with Debug::{to_repr}

///|
#deprecated
pub extend GraphDataValue with Debug::{to_repr}

///|
#deprecated
pub extend GraphDataValue with Eq::{not_equal, equal}

///|
#deprecated
pub extend GraphInput with Debug::{to_repr}

///|
#deprecated
pub extend GraphModel with Debug::{to_repr}

///|
#deprecated
pub extend LayerInput with Debug::{to_repr}

///|
#deprecated
pub extend LayerModel with Debug::{to_repr}

///|
#deprecated
pub extend LayoutPatch with Debug::{to_repr}

///|
#deprecated
pub extend Legend with Debug::{to_repr}

///|
#deprecated
pub extend LegendEntry with Debug::{to_repr}

///|
#deprecated
pub extend LegendEntryInput with Debug::{to_repr}

///|
#deprecated
pub extend LegendInput with Debug::{to_repr}

///|
#deprecated
pub extend LegendModel with Debug::{to_repr}

///|
#deprecated
pub extend LegendPosition with Debug::{to_repr}

///|
#deprecated
pub extend LegendPosition with Eq::{not_equal, equal}

///|
#deprecated
pub extend ObjectInput with Debug::{to_repr}

///|
#deprecated
pub extend ObjectModel with Debug::{to_repr}

///|
#deprecated
pub extend ObjectReference with Debug::{to_repr}

///|
#deprecated
pub extend ObjectReference with Eq::{not_equal, equal}

///|
#deprecated
pub extend Point with Debug::{to_repr}

///|
#deprecated
pub extend Point with Eq::{not_equal, equal}

///|
#deprecated
pub extend Point with Show::{output}

///|
#deprecated
pub extend Route with Debug::{to_repr}

///|
#deprecated
pub extend RouteStyle with Debug::{to_repr}

///|
#deprecated
pub extend RouteStyle with Eq::{not_equal, equal}

///|
#deprecated
pub extend ScenarioInput with Debug::{to_repr}

///|
#deprecated
pub extend ScenarioModel with Debug::{to_repr}

///|
#deprecated
pub extend SequenceFragmentInput with Debug::{to_repr}

///|
#deprecated
pub extend SequenceFragmentLayout with Debug::{to_repr}

///|
#deprecated
pub extend SequenceFragmentModel with Debug::{to_repr}

///|
#deprecated
pub extend ShapeType with Debug::{to_repr}

///|
#deprecated
pub extend ShapeType with Eq::{not_equal, equal}

///|
#deprecated
pub extend StepInput with Debug::{to_repr}

///|
#deprecated
pub extend StepModel with Debug::{to_repr}

///|
#deprecated
pub extend StyleInput with Debug::{to_repr}

///|
#deprecated
pub extend StyleInput with Eq::{not_equal, equal}

///|
#deprecated
pub extend StyleModel with Debug::{to_repr}

///|
#deprecated
pub extend StyleModel with Eq::{not_equal, equal}

///|
#deprecated
pub extend StyleValue with Debug::{to_repr}

///|
#deprecated
pub extend StyleValue with Eq::{not_equal, equal}

///|
#deprecated
pub extend Waypoint with Debug::{to_repr}
