// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
#deprecated
pub extend CompileError with Debug::{to_repr}

///|
#deprecated
pub extend CompileError with Eq::{not_equal, equal}

///|
#deprecated
pub extend CompileError with Show::{output}

///|
#deprecated
pub extend Composite with Debug::{to_repr}

///|
#deprecated
pub extend Composite with Eq::{not_equal, equal}

///|
#deprecated
pub extend Edge with Debug::{to_repr}

///|
#deprecated
pub extend Edge with Eq::{not_equal, equal}

///|
#deprecated
pub extend EdgeID with Debug::{to_repr}

///|
#deprecated
pub extend EdgeID with Eq::{not_equal, equal}

///|
#deprecated
pub extend EdgeReference with Debug::{to_repr}

///|
#deprecated
pub extend EdgeReference with Eq::{not_equal, equal}

///|
#deprecated
pub extend Field with Debug::{to_repr}

///|
#deprecated
pub extend Field with Eq::{not_equal, equal}

///|
#deprecated
pub extend FieldReference with Debug::{to_repr}

///|
#deprecated
pub extend FieldReference with Eq::{not_equal, equal}

///|
#deprecated
pub extend IRArray with Debug::{to_repr}

///|
#deprecated
pub extend IRArray with Eq::{not_equal, equal}

///|
#deprecated
pub extend Map with Debug::{to_repr}

///|
#deprecated
pub extend Map with Eq::{not_equal, equal}

///|
#deprecated
pub extend Node with Debug::{to_repr}

///|
#deprecated
pub extend Node with Eq::{not_equal, equal}

///|
#deprecated
pub extend NodePath with Debug::{to_repr}

///|
#deprecated
pub extend NodePath with Eq::{not_equal, equal}

///|
#deprecated
pub extend NodePathSegment with Debug::{to_repr}

///|
#deprecated
pub extend NodePathSegment with Eq::{not_equal, equal}

///|
#deprecated
pub extend RefContext with Debug::{to_repr}

///|
#deprecated
pub extend RefContext with Eq::{not_equal, equal}

///|
#deprecated
pub extend Reference with Debug::{to_repr}

///|
#deprecated
pub extend Reference with Eq::{not_equal, equal}

///|
#deprecated
pub extend Scalar with Debug::{to_repr}

///|
#deprecated
pub extend Scalar with Eq::{not_equal, equal}

///|
#deprecated
pub extend ScalarValue with Debug::{to_repr}

///|
#deprecated
pub extend ScalarValue with Eq::{not_equal, equal}

///|
#deprecated
pub extend Value with Debug::{to_repr}

///|
#deprecated
pub extend Value with Eq::{not_equal, equal}
