// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
#deprecated
pub extend ArrayNode with Debug::{to_repr}

///|
#deprecated
pub extend ArrayNode with Eq::{not_equal, equal}

///|
#deprecated
pub extend ArrayValue with Debug::{to_repr}

///|
#deprecated
pub extend ArrayValue with Eq::{not_equal, equal}

///|
#deprecated
pub extend BlockString with Debug::{to_repr}

///|
#deprecated
pub extend BlockString with Eq::{not_equal, equal}

///|
#deprecated
pub extend DoubleQuotedString with Debug::{to_repr}

///|
#deprecated
pub extend DoubleQuotedString with Eq::{not_equal, equal}

///|
#deprecated
pub extend Edge with Debug::{to_repr}

///|
#deprecated
pub extend Edge with Eq::{not_equal, equal}

///|
#deprecated
pub extend EdgeIndex with Debug::{to_repr}

///|
#deprecated
pub extend EdgeIndex with Eq::{not_equal, equal}

///|
#deprecated
pub extend Import with Debug::{to_repr}

///|
#deprecated
pub extend Import with Eq::{not_equal, equal}

///|
#deprecated
pub extend Interpolation with Debug::{to_repr}

///|
#deprecated
pub extend Interpolation with Eq::{not_equal, equal}

///|
#deprecated
pub extend Key with Debug::{to_repr}

///|
#deprecated
pub extend Key with Eq::{not_equal, equal}

///|
#deprecated
pub extend KeyPath with Debug::{to_repr}

///|
#deprecated
pub extend KeyPath with Eq::{not_equal, equal}

///|
#deprecated
pub extend Map with Debug::{to_repr}

///|
#deprecated
pub extend Map with Eq::{not_equal, equal}

///|
#deprecated
pub extend MapNode with Debug::{to_repr}

///|
#deprecated
pub extend MapNode with Eq::{not_equal, equal}

///|
#deprecated
pub extend Node with Debug::{to_repr}

///|
#deprecated
pub extend Node with Eq::{not_equal, equal}

///|
#deprecated
pub extend Scalar with Debug::{to_repr}

///|
#deprecated
pub extend Scalar with Eq::{not_equal, equal}

///|
#deprecated
pub extend StringValue with Debug::{to_repr}

///|
#deprecated
pub extend StringValue with Eq::{not_equal, equal}

///|
#deprecated
pub extend Substitution with Debug::{to_repr}

///|
#deprecated
pub extend Substitution with Eq::{not_equal, equal}

///|
#deprecated
pub extend UnquotedString with Debug::{to_repr}

///|
#deprecated
pub extend UnquotedString with Eq::{not_equal, equal}

///|
#deprecated
pub extend Value with Debug::{to_repr}

///|
#deprecated
pub extend Value with Eq::{not_equal, equal}
