// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
#deprecated
pub extend Element with Show::{output}

///|
#deprecated
pub extend XmlElement with Debug::{to_repr}

///|
#deprecated
pub extend XmlElement with Eq::{not_equal, equal}

///|
#deprecated
pub extend XmlNode with Debug::{to_repr}

///|
#deprecated
pub extend XmlNode with Eq::{not_equal, equal}
